using TestCase.Basic.Addition.Simd;
using TestCase.Basic.Division.Simd;
using TestCase.Basic.Multiplication.Simd;
using TestCase.Basic.Subtraction.Simd;
using TestRunner;
using TestRunner.Generator;
using TestRunner.Generator.Interfaces;
using TestRunner.Wrappers.Base;
using TestRunner.Wrappers.Base.Config;
using Unity.Collections;
using Unity.Mathematics;
using WorkSpace.Tests.Base;

namespace WorkSpace.Tests
{
    public class BasicSimdTest : SampleGenerator
    {
        private const string TestName = nameof(BasicSimdTest);

        public override ISampleConfig[] InitSampleConfigs()
        {
            return new ISampleConfig[]
            {
                new SampleConfig(typeof(int2), DataConfig.DataInt2),
                new SampleConfig(typeof(int3), DataConfig.DataInt3),
                new SampleConfig(typeof(int4), DataConfig.DataInt4),
                new SampleConfig(typeof(float2), DataConfig.DataFloat2),
                new SampleConfig(typeof(float3), DataConfig.DataFloat3),
                new SampleConfig(typeof(float4), DataConfig.DataFloat4),
                new SampleConfig(typeof(uint2), DataConfig.DataUInt2),
                new SampleConfig(typeof(uint3), DataConfig.DataUInt3),
                new SampleConfig(typeof(uint4), DataConfig.DataUInt4),
            };
        }

        public override IWorkWrapper[] InitWorkWrappers(IInputDataContainer inputDataContainer, int dataSize)
        {
            return new[]
            {
                #region Addition

                WorkerTests<int2, int2, int2>.RunIJob(TestName, new SimdAdditionInt2Job(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunIJobParallelFor(TestName, new SimdAdditionInt2JobParallelFor(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunINonJob(TestName, new SimdAdditionInt2NonJob(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2)),

                WorkerTests<int3, int3, int3>.RunIJob(TestName, new SimdAdditionInt3Job(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunIJobParallelFor(TestName, new SimdAdditionInt3JobParallelFor(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunINonJob(TestName, new SimdAdditionInt3NonJob(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3)),

                WorkerTests<int4, int4, int4>.RunIJob(TestName, new SimdAdditionInt4Job(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunIJobParallelFor(TestName, new SimdAdditionInt4JobParallelFor(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunINonJob(TestName, new SimdAdditionInt4NonJob(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4)),

                WorkerTests<uint2, uint2, uint2>.RunIJob(TestName, new SimdAdditionUInt2Job(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunIJobParallelFor(TestName, new SimdAdditionUInt2JobParallelFor(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunINonJob(TestName, new SimdAdditionUInt2NonJob(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2)),

                WorkerTests<uint3, uint3, uint3>.RunIJob(TestName, new SimdAdditionUInt3Job(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunIJobParallelFor(TestName, new SimdAdditionUInt3JobParallelFor(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunINonJob(TestName, new SimdAdditionUInt3NonJob(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3)),

                WorkerTests<uint4, uint4, uint4>.RunIJob(TestName, new SimdAdditionUInt4Job(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunIJobParallelFor(TestName, new SimdAdditionUInt4JobParallelFor(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunINonJob(TestName, new SimdAdditionUInt4NonJob(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4)),

                WorkerTests<float2, float2, float2>.RunIJob(TestName, new SimdAdditionFloat2Job(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunIJobParallelFor(TestName, new SimdAdditionFloat2JobParallelFor(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunINonJob(TestName, new SimdAdditionFloat2NonJob(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2)),

                WorkerTests<float3, float3, float3>.RunIJob(TestName, new SimdAdditionFloat3Job(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunIJobParallelFor(TestName, new SimdAdditionFloat3JobParallelFor(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunINonJob(TestName, new SimdAdditionFloat3NonJob(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3)),

                WorkerTests<float4, float4, float4>.RunIJob(TestName, new SimdAdditionFloat4Job(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunIJobParallelFor(TestName, new SimdAdditionFloat4JobParallelFor(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunINonJob(TestName, new SimdAdditionFloat4NonJob(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4)),

                #endregion

                #region Division

                WorkerTests<int2, int2, int2>.RunIJob(TestName, new SimdDivisionInt2Job(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunIJobParallelFor(TestName, new SimdDivisionInt2JobParallelFor(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunINonJob(TestName, new SimdDivisionInt2NonJob(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2)),

                WorkerTests<int3, int3, int3>.RunIJob(TestName, new SimdDivisionInt3Job(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunIJobParallelFor(TestName, new SimdDivisionInt3JobParallelFor(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunINonJob(TestName, new SimdDivisionInt3NonJob(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3)),

                WorkerTests<int4, int4, int4>.RunIJob(TestName, new SimdDivisionInt4Job(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunIJobParallelFor(TestName, new SimdDivisionInt4JobParallelFor(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunINonJob(TestName, new SimdDivisionInt4NonJob(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4)),

                WorkerTests<uint2, uint2, uint2>.RunIJob(TestName, new SimdDivisionUInt2Job(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunIJobParallelFor(TestName, new SimdDivisionUInt2JobParallelFor(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunINonJob(TestName, new SimdDivisionUInt2NonJob(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2)),

                WorkerTests<uint3, uint3, uint3>.RunIJob(TestName, new SimdDivisionUInt3Job(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunIJobParallelFor(TestName, new SimdDivisionUInt3JobParallelFor(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunINonJob(TestName, new SimdDivisionUInt3NonJob(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3)),

                WorkerTests<uint4, uint4, uint4>.RunIJob(TestName, new SimdDivisionUInt4Job(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunIJobParallelFor(TestName, new SimdDivisionUInt4JobParallelFor(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunINonJob(TestName, new SimdDivisionUInt4NonJob(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4)),

                WorkerTests<float2, float2, float2>.RunIJob(TestName, new SimdDivisionFloat2Job(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunIJobParallelFor(TestName, new SimdDivisionFloat2JobParallelFor(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunINonJob(TestName, new SimdDivisionFloat2NonJob(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2)),

                WorkerTests<float3, float3, float3>.RunIJob(TestName, new SimdDivisionFloat3Job(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunIJobParallelFor(TestName, new SimdDivisionFloat3JobParallelFor(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunINonJob(TestName, new SimdDivisionFloat3NonJob(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3)),

                WorkerTests<float4, float4, float4>.RunIJob(TestName, new SimdDivisionFloat4Job(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunIJobParallelFor(TestName, new SimdDivisionFloat4JobParallelFor(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunINonJob(TestName, new SimdDivisionFloat4NonJob(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4)),

                #endregion

                #region Multiplication

                WorkerTests<int2, int2, int2>.RunIJob(TestName, new SimdMultiplicationInt2Job(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunIJobParallelFor(TestName, new SimdMultiplicationInt2JobParallelFor(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunINonJob(TestName, new SimdMultiplicationInt2NonJob(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2)),

                WorkerTests<int3, int3, int3>.RunIJob(TestName, new SimdMultiplicationInt3Job(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunIJobParallelFor(TestName, new SimdMultiplicationInt3JobParallelFor(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunINonJob(TestName, new SimdMultiplicationInt3NonJob(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3)),

                WorkerTests<int4, int4, int4>.RunIJob(TestName, new SimdMultiplicationInt4Job(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunIJobParallelFor(TestName, new SimdMultiplicationInt4JobParallelFor(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunINonJob(TestName, new SimdMultiplicationInt4NonJob(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4)),

                WorkerTests<uint2, uint2, uint2>.RunIJob(TestName, new SimdMultiplicationUInt2Job(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationUInt2JobParallelFor(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunINonJob(TestName, new SimdMultiplicationUInt2NonJob(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2)),

                WorkerTests<uint3, uint3, uint3>.RunIJob(TestName, new SimdMultiplicationUInt3Job(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationUInt3JobParallelFor(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunINonJob(TestName, new SimdMultiplicationUInt3NonJob(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3)),

                WorkerTests<uint4, uint4, uint4>.RunIJob(TestName, new SimdMultiplicationUInt4Job(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationUInt4JobParallelFor(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunINonJob(TestName, new SimdMultiplicationUInt4NonJob(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4)),

                WorkerTests<float2, float2, float2>.RunIJob(TestName, new SimdMultiplicationFloat2Job(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationFloat2JobParallelFor(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunINonJob(TestName, new SimdMultiplicationFloat2NonJob(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2)),

                WorkerTests<float3, float3, float3>.RunIJob(TestName, new SimdMultiplicationFloat3Job(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationFloat3JobParallelFor(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunINonJob(TestName, new SimdMultiplicationFloat3NonJob(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3)),

                WorkerTests<float4, float4, float4>.RunIJob(TestName, new SimdMultiplicationFloat4Job(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunIJobParallelFor(TestName,
                    new SimdMultiplicationFloat4JobParallelFor(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunINonJob(TestName, new SimdMultiplicationFloat4NonJob(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4)),

                #endregion

                #region Subtraction

                WorkerTests<int2, int2, int2>.RunIJob(TestName, new SimdSubtractionInt2Job(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunIJobParallelFor(TestName, new SimdSubtractionInt2JobParallelFor(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int2, int2, int2>.RunINonJob(TestName, new SimdSubtractionInt2NonJob(),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2),
                    inputDataContainer.GetData<int2>(DataConfig.DataInt2)),

                WorkerTests<int3, int3, int3>.RunIJob(TestName, new SimdSubtractionInt3Job(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunIJobParallelFor(TestName, new SimdSubtractionInt3JobParallelFor(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int3, int3, int3>.RunINonJob(TestName, new SimdSubtractionInt3NonJob(),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3),
                    inputDataContainer.GetData<int3>(DataConfig.DataInt3)),

                WorkerTests<int4, int4, int4>.RunIJob(TestName, new SimdSubtractionInt4Job(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4), new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunIJobParallelFor(TestName, new SimdSubtractionInt4JobParallelFor(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<int4, int4, int4>.RunINonJob(TestName, new SimdSubtractionInt4NonJob(),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4),
                    inputDataContainer.GetData<int4>(DataConfig.DataInt4)),

                WorkerTests<uint2, uint2, uint2>.RunIJob(TestName, new SimdSubtractionUInt2Job(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunIJobParallelFor(TestName, new SimdSubtractionUInt2JobParallelFor(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint2, uint2, uint2>.RunINonJob(TestName, new SimdSubtractionUInt2NonJob(),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2),
                    inputDataContainer.GetData<uint2>(DataConfig.DataUInt2)),

                WorkerTests<uint3, uint3, uint3>.RunIJob(TestName, new SimdSubtractionUInt3Job(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunIJobParallelFor(TestName, new SimdSubtractionUInt3JobParallelFor(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint3, uint3, uint3>.RunINonJob(TestName, new SimdSubtractionUInt3NonJob(),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3),
                    inputDataContainer.GetData<uint3>(DataConfig.DataUInt3)),

                WorkerTests<uint4, uint4, uint4>.RunIJob(TestName, new SimdSubtractionUInt4Job(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunIJobParallelFor(TestName, new SimdSubtractionUInt4JobParallelFor(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<uint4, uint4, uint4>.RunINonJob(TestName, new SimdSubtractionUInt4NonJob(),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4),
                    inputDataContainer.GetData<uint4>(DataConfig.DataUInt4)),

                WorkerTests<float2, float2, float2>.RunIJob(TestName, new SimdSubtractionFloat2Job(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunIJobParallelFor(TestName,
                    new SimdSubtractionFloat2JobParallelFor(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float2, float2, float2>.RunINonJob(TestName, new SimdSubtractionFloat2NonJob(),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2),
                    inputDataContainer.GetData<float2>(DataConfig.DataFloat2)),

                WorkerTests<float3, float3, float3>.RunIJob(TestName, new SimdSubtractionFloat3Job(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunIJobParallelFor(TestName,
                    new SimdSubtractionFloat3JobParallelFor(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float3, float3, float3>.RunINonJob(TestName, new SimdSubtractionFloat3NonJob(),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3),
                    inputDataContainer.GetData<float3>(DataConfig.DataFloat3)),

                WorkerTests<float4, float4, float4>.RunIJob(TestName, new SimdSubtractionFloat4Job(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJob(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunIJobParallelFor(TestName,
                    new SimdSubtractionFloat4JobParallelFor(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    new WorkConfigIJobParallelFor(Allocator.Persistent)),
                WorkerTests<float4, float4, float4>.RunINonJob(TestName, new SimdSubtractionFloat4NonJob(),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4),
                    inputDataContainer.GetData<float4>(DataConfig.DataFloat4)),

                #endregion
            };
        }
    }
}